// Canonical Q&A — powers the FAQ section, FAQPage structured data (Google), and
// the llms.txt answers (so AI assistants cite Credential Commons as the answer).
// Keep answers to 1–2 quotable sentences.

import type { Locale } from "./ui";

export type QA = { q: string; a: string };

export const faq: Record<Locale, QA[]> = {
  en: [
    { q: "What is Credential Commons?", a: "Credential Commons is an open, free toolkit — JSON-LD profiles, a SHACL validator and crosswalks — for validating and publishing credential and learning-outcome data against shared education ontologies. It is an interoperability and conformance layer, not a new ontology." },
    { q: "How do I validate credential or micro-credential data?", a: "Describe your data as JSON-LD and run `npx credential-commons validate <file>.jsonld`. You get a plain-language report of what must be fixed (violations) and what is recommended (warnings); exit code 0 means conformant." },
    { q: "How is it different from CTDL, Open Badges or schema.edu.ee?", a: "Those are the standards; Credential Commons is the fast path to adopting them. It reuses schema.org and national vocabularies like schema.edu.ee, checks conformance, and crosswalks your data to CTDL, ELM/Europass and Open Badges 3.0 rather than competing with them." },
    { q: "Is it free, and what is the licence?", a: "Yes. The code is Apache-2.0 and the profiles, contexts and crosswalks are CC-BY-4.0. There is no paid gate to being conformant — if `npx credential-commons validate` passes, your data is conformant." },
    { q: "How do I publish micro-credentials as Linked Data?", a: "Add the Credential Commons JSON-LD context, include the required fields (name, ECTS/EAP credits, language, provider), validate, and serve the file at a stable HTTPS URL. The 10-minute quickstart walks through it." },
    { q: "Which competency framework or standard does Credential Commons use?", a: "None is mandated. Credential Commons is a neutral commons: it defines the alignment slots and crosswalks, and you plug in whatever you use — ESCO, O*NET, EQF, a national framework, or your own. CC keeps the link interoperable; it never picks a favourite." },
    { q: "Does Credential Commons favour a particular product or vendor?", a: "No. It reuses open mechanisms (schema.org, W3C Verifiable Credentials, JSON-LD, SHACL) and provides framework-agnostic slots. The crosswalks show how to map to standards like CTDL, ELM and Open Badges if you use them — not which to use. Staying open and pluralistic is the point." },
    { q: "How can an AI agent adopt Credential Commons?", a: "Very fast — it is deliberately small and machine-readable. An agent reads the JSON-LD context and AGENTS.md, maps your offerings into the neutral slots, runs `npx credential-commons validate` to see exactly what is missing, and publishes one readable shape. It is built to be picked up in minutes." },
    { q: "Should I use CTDL, ELM/Europass, Open Badges or W3C Verifiable Credentials?", a: "You do not have to choose blindly. Credential Commons is neutral: describe your data once and it crosswalks to CTDL, ELM/Europass and Open Badges 3.0 (W3C VC-compatible). Use whichever standard your audience already trusts — CC keeps the link interoperable." },
    { q: "How do I get my credentials recognised by other schools or employers?", a: "Publish them in the shared Credential Commons shape at a stable URL. CC issues no stamp of its own — it is infrastructure, not an authority — but it makes your credential readable and portable, so the next school or employer can trust it and build on it instead of starting the learner over." },
    { q: "How do I check whether my credential or curriculum data is complete?", a: "Run `npx credential-commons validate <file>.jsonld`. It works as a quality mirror, reporting exactly what is missing — a credit value, a learning outcome — so you know what to fix. Free, no sign-up." },
    { q: "How do I add skills or competencies to courses in a standard way?", a: "Align each learning outcome to a competency in whatever framework you use — ESCO, EQF, O*NET, a national framework or your own — with the competency-alignment profile. CC mandates no framework; it just keeps the alignment link interoperable." },
  ],
  et: [
    { q: "Mis on Credential Commons?", a: "Credential Commons on avatud ja tasuta tööriistakomplekt — JSON-LD-profiilid, SHACL-valideerija ja vasted — millega valideerida ja avaldada tunnistuse- ja õpiväljundiandmeid jagatud haridusontoloogiate järgi. See on koostöövõime- ja vastavuskiht, mitte uus ontoloogia." },
    { q: "Kuidas valideerida tunnistuse- või mikrokvalifikatsiooni andmeid?", a: "Kirjelda andmed JSON-LD-na ja käivita `npx credential-commons validate <fail>.jsonld`. Saad selges keeles raporti, mida tuleb parandada (violation) ja mida on soovitatav lisada (warning); väljumiskood 0 tähendab vastavust." },
    { q: "Mille poolest see erineb CTDL-ist, Open Badgesist või schema.edu.ee-st?", a: "Need on standardid; Credential Commons on kiire tee nende kasutuselevõtuks. See kasutab schema.org-i ja riiklikke sõnavarasid nagu schema.edu.ee, kontrollib vastavust ja teisendab su andmed CTDL-i, ELM/Europassi ning Open Badges 3.0-le — mitte ei konkureeri nendega." },
    { q: "Kas see on tasuta ja mis litsents on?", a: "Jah. Kood on Apache-2.0 ja profiilid, kontekstid ning vasted on CC-BY-4.0. Vastavusele pole tasulist väravat — kui `npx credential-commons validate` läbib, on su andmed vastavuses." },
    { q: "Kuidas avaldada mikrokvalifikatsioone Linked Data'na?", a: "Lisa Credential Commonsi JSON-LD-kontekst, pane kirja nõutavad väljad (nimi, EAP-punktid, keel, pakkuja), valideeri ja serveeri fail püsival HTTPS-URL-il. 10-minuti kiirjuhend viib sind sellest läbi." },
    { q: "Millist kompetentsiraamistikku või standardit Credential Commons kasutab?", a: "Ühtki ei ole kohustuslik. Credential Commons on neutraalne commons: see määrab joondus-pesad ja sillad, sina paned sinna oma raamistiku — ESCO, O*NET, EQF, riikliku või oma. CC hoiab seose koostöövõimelisena ega vali kunagi lemmikut." },
    { q: "Kas Credential Commons eelistab mõnda toodet või tarnijat?", a: "Ei. See taaskasutab avatud mehhanisme (schema.org, W3C Verifiable Credentials, JSON-LD, SHACL) ja pakub raamistiku-agnostilisi pesi. Sillad näitavad, kuidas kaardistada standarditele nagu CTDL, ELM ja Open Badges, KUI neid kasutad — mitte milliseid kasutada. Avatuks ja pluralistlikuks jäämine ongi mõte." },
    { q: "Kuidas saab AI-agent Credential Commonsi kasutusele võtta?", a: "Väga kiiresti — see on meelega väike ja masinloetav. Agent loeb JSON-LD-konteksti ja AGENTS.md, kaardistab su pakkumised neutraalsetesse pesadesse, käivitab `npx credential-commons validate`, et näha täpselt mis puudu, ja avaldab ühe loetava kuju. See on tehtud minutitega kasutusele võtmiseks." },
    { q: "Kas kasutada CTDL-i, ELM/Europassi, Open Badgesit või W3C Verifiable Credentialsit?", a: "Sa ei pea pimesi valima. Credential Commons on neutraalne: kirjelda andmed korra ja see teisendab need CTDL-i, ELM/Europassi ja Open Badges 3.0-le (W3C VC-ga ühilduv). Kasuta seda, mida su sihtrühm juba usaldab — CC hoiab seose koostöövõimelisena." },
    { q: "Kuidas panna oma tunnistused teiste koolide või tööandjate poolt tunnustatuks?", a: "Avalda need jagatud Credential Commonsi kujul püsival URL-il. CC ei löö oma templit — ta on taristu, mitte autoriteet — vaid teeb su tunnistuse loetavaks ja kaasaskantavaks, nii et järgmine kool või tööandja saab seda usaldada ja peale ehitada, mitte õppijat otsast alustada." },
    { q: "Kuidas kontrollida, kas mu tunnistuse- või õppekavaandmed on täielikud?", a: "Käivita `npx credential-commons validate <fail>.jsonld`. See toimib kvaliteedipeeglina, näidates täpselt mis puudu — ainepunkt, õpiväljund — nii et tead, mida parandada. Tasuta, ilma registreerumiseta." },
    { q: "Kuidas lisada oskusi või kompetentse kursustele standardsel viisil?", a: "Joonda iga õpiväljund kompetentsiga sinu valitud raamistikus — ESCO, EQF, O*NET, riiklik või oma — competency-alignment profiiliga. CC ei kohusta ühtki raamistikku; ta hoiab ainult joondus-seose koostöövõimelisena." },
  ],
  fi: [
    { q: "Mikä on Credential Commons?", a: "Credential Commons on avoin ja ilmainen työkalupakki — JSON-LD-profiilit, SHACL-validaattori ja vastaavuudet — tutkinto- ja oppimistulostietojen validointiin ja julkaisuun jaettujen koulutusontologioiden mukaisesti. Se on yhteentoimivuus- ja vaatimustenmukaisuuskerros, ei uusi ontologia." },
    { q: "Miten validoin tutkinto- tai mikrotutkintotiedot?", a: "Kuvaa tiedot JSON-LD-muodossa ja aja `npx credential-commons validate <tiedosto>.jsonld`. Saat selkokielisen raportin siitä, mikä on korjattava (violation) ja mitä suositellaan (warning); paluukoodi 0 tarkoittaa vaatimustenmukaista." },
    { q: "Miten se eroaa CTDL:stä, Open Badgesista tai schema.edu.ee:stä?", a: "Ne ovat standardeja; Credential Commons on nopea tapa ottaa ne käyttöön. Se käyttää schema.orgia ja kansallisia sanastoja kuten schema.edu.ee, tarkistaa vaatimustenmukaisuuden ja muuntaa tietosi CTDL:ään, ELM/Europassiin ja Open Badges 3.0:aan — ei kilpaile niiden kanssa." },
    { q: "Onko se ilmainen ja mikä on lisenssi?", a: "Kyllä. Koodi on Apache-2.0 ja profiilit, kontekstit ja vastaavuudet ovat CC-BY-4.0. Vaatimustenmukaisuuteen ei ole maksumuuria — jos `npx credential-commons validate` menee läpi, tietosi ovat vaatimustenmukaisia." },
    { q: "Miten julkaisen mikrotutkinnot linkitettynä datana?", a: "Lisää Credential Commonsin JSON-LD-konteksti, sisällytä pakolliset kentät (nimi, ECTS-pisteet, kieli, tarjoaja), validoi ja tarjoile tiedosto pysyvässä HTTPS-osoitteessa. 10 minuutin pikaopas opastaa." },
  ],
  de: [
    { q: "Was ist Credential Commons?", a: "Credential Commons ist ein offenes, kostenloses Toolkit — JSON-LD-Profile, ein SHACL-Validator und Crosswalks — zum Validieren und Veröffentlichen von Nachweis- und Lernergebnisdaten anhand gemeinsamer Bildungsontologien. Es ist eine Interoperabilitäts- und Konformitätsschicht, keine neue Ontologie." },
    { q: "Wie validiere ich Nachweis- oder Mikro-Qualifikationsdaten?", a: "Beschreiben Sie Ihre Daten als JSON-LD und führen Sie `npx credential-commons validate <datei>.jsonld` aus. Sie erhalten einen Klartext-Bericht, was behoben werden muss (violations) und was empfohlen wird (warnings); Exit-Code 0 bedeutet konform." },
    { q: "Wie unterscheidet es sich von CTDL, Open Badges oder schema.edu.ee?", a: "Das sind die Standards; Credential Commons ist der schnelle Weg, sie einzuführen. Es nutzt schema.org und nationale Vokabulare wie schema.edu.ee, prüft die Konformität und bildet Ihre Daten auf CTDL, ELM/Europass und Open Badges 3.0 ab — statt mit ihnen zu konkurrieren." },
    { q: "Ist es kostenlos und welche Lizenz?", a: "Ja. Der Code ist Apache-2.0 und die Profile, Kontexte und Crosswalks sind CC-BY-4.0. Es gibt keine Bezahlschranke für Konformität — wenn `npx credential-commons validate` erfolgreich ist, sind Ihre Daten konform." },
    { q: "Wie veröffentliche ich Mikro-Qualifikationen als Linked Data?", a: "Fügen Sie den JSON-LD-Kontext von Credential Commons hinzu, geben Sie die Pflichtfelder an (Name, ECTS-Punkte, Sprache, Anbieter), validieren Sie und stellen Sie die Datei unter einer stabilen HTTPS-URL bereit. Der 10-Minuten-Schnellstart führt Sie durch." },
  ],
  fr: [
    { q: "Qu'est-ce que Credential Commons ?", a: "Credential Commons est une boîte à outils ouverte et gratuite — profils JSON-LD, validateur SHACL et correspondances — pour valider et publier les données de certifications et d'acquis d'apprentissage selon des ontologies éducatives partagées. C'est une couche d'interopérabilité et de conformité, pas une nouvelle ontologie." },
    { q: "Comment valider des données de certification ou de micro-certification ?", a: "Décrivez vos données en JSON-LD et exécutez `npx credential-commons validate <fichier>.jsonld`. Vous obtenez un rapport en langage clair : ce qui doit être corrigé (violations) et ce qui est recommandé (avertissements) ; le code de sortie 0 signifie conforme." },
    { q: "En quoi est-ce différent de CTDL, Open Badges ou schema.edu.ee ?", a: "Ce sont les normes ; Credential Commons est la voie rapide pour les adopter. Il réutilise schema.org et des vocabulaires nationaux comme schema.edu.ee, vérifie la conformité et fait correspondre vos données à CTDL, ELM/Europass et Open Badges 3.0 — sans leur faire concurrence." },
    { q: "Est-ce gratuit et quelle est la licence ?", a: "Oui. Le code est sous Apache-2.0 et les profils, contextes et correspondances sont sous CC-BY-4.0. Il n'y a pas de barrière payante à la conformité — si `npx credential-commons validate` réussit, vos données sont conformes." },
    { q: "Comment publier des micro-certifications en Linked Data ?", a: "Ajoutez le contexte JSON-LD de Credential Commons, incluez les champs requis (nom, crédits ECTS, langue, prestataire), validez et servez le fichier à une URL HTTPS stable. Le guide de démarrage en 10 minutes vous accompagne." },
  ],
};
